### ISSUE TITLE
Port gci-java to new gci-proxy

### ISSUE THREAD

**Issue by danielfireman** [gcinterceptor/gci-java#22]
There would be a lot clean up, much of what gci-java does is done by gci-proxy now.

You can find the protocol description [here](https://github.com/gcinterceptor/gci-proxy). You can get inspiration from [gci-go](https://github.com/gcinterceptor/gci-go/blob/master/httphandler/handler.go).

**Comment by danielfireman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Porting gci-java to new proxy protocol](https://trello.com/c/xBLU7TlT/1-porting-gci-java-to-new-proxy-protocol)

**Comment by dfquaresma** [comment]
Closed this in #23
